steps:
- name: cypress/included:8.5.0
  entrypoint: npm
  args: ['ci']
  dir: test
- name: cypress/included:8.5.0
  entrypoint: npm
  env:
  - 'CYPRESS_API_URL=https://cypress-director-gp34ticnkq-ey.a.run.app'
  - 'APP_VERSION=2.2.2'
  args: ['run', 'ci']
  dir: test