steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deploy'
  args: ['app', 'deploy']
- name: 'gcr.io/cloud-builders/curl'
  args: ['http://teamcity.jovanilic.com/app/rest/buildQueue', '-H', 'Authorization: Bearer eyJ0eXAiOiAiVENWMiJ9.MHM4NEI2Nms5MVJqekg2MXVUSDRtdzJsZ1Z3.M2I5Njc2ZWItMjI5Yi00NGM0LWI2OGQtOThkZTI4ODFmZjBj', '-H', 'Content-Type:application/xml', '-d', '<build><buildType id="quotes_cypress"/></build>', '-X', 'POST']
  secretEnv: ['TOKEN']
  waitFor: ['deploy']
availableSecrets:
  secretManager:
  - versionName: projects/307352298506/secrets/teamcity-token/versions/latest
    env: 'TOKEN'
timeout: 1600s