steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
  - name: cypress/included:8.7.0
    entrypoint: npm
    args: ['ci']
  - name: cypress/included:8.7.0
    entrypoint: npm
    env:
      - 'CYPRESS_API_URL=https://cypress-director-gp34ticnkq-ey.a.run.app'
    args: ['run', 'ci']
timeout: 1800s
