steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
- name: cypress/included:8.7.0
  entrypoint: npm
  args: ['ci']
  dir: test
- name: cypress/included:8.7.0
  entrypoint: npm
  env:
  - 'CYPRESS_API_URL=https://cypress-director-gp34ticnkq-ey.a.run.app'
  - 'APP_VERSION=3.0.1'
  args: ['run', 'ci']
  dir: test
timeout: 1800s