steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deploy'
  args: ['app', 'deploy']
- name: 'gcr.io/cloud-builders/curl'
  args: ['http://teamcity.jovanilic.com/app/rest/buildQueue', '-H', 'Authorization: Bearer $$TOKEN', '-H', 'Content-Type:application/xml', '-d', '<build><buildType id="quotes_cypress"/></build>', '-X', 'POST']
  secretEnv: ['TOKEN']
  waitFor: ['deploy']
availableSecrets:
  secretManager:
  - versionName: projects/307352298506/secrets/teamcity-token/versions/1
    env: 'TOKEN'
timeout: 1600s